name: GitHub Actions Demo
run-name: "${{ github.actor }} is testing out GitHub Actions \U0001F680"
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Save SQL file names to variable
        id: save-sql-file-names
        run: >
          changed_sql_files=$(git diff --name-only -- "*.sql" ${{
          github.event.before }} ${{ github.sha }})

          echo "CHANGED_SQL_FILES=$changed_sql_files" >> $GITHUB_ENV
      - name: Use git diff variable and call Python script
        env:
          CHANGED_SQL_FILES: '${{ env.CHANGED_SQL_FILES }}'
        run: |
          echo "Git Diff (SQL only) Files: "
          echo "$CHANGED_SQL_FILES"

          # Assuming you have 'extract_sql_files.py' available
          python extract_sql_files.py "$CHANGED_SQL_FILES"
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Save SQL file names to variable
        id: save-sql-file-names
        run: >
          changed_sql_files=$(git diff --name-only -- "*.sql" ${{
          github.event.before }} ${{ github.sha }})

          echo "CHANGED_SQL_FILES=$changed_sql_files" >> $GITHUB_ENV
      - name: Use git diff variable and call Python script
        env:
          CHANGED_SQL_FILES: '${{ env.CHANGED_SQL_FILES }}'
        run: |
          echo "Git Diff (SQL only) Files: "
          echo "$CHANGED_SQL_FILES"

          # Call Python script with the git diff as an argument
          python extract_sql_files.py "$CHANGED_SQL_FILES"
